name: home-lib-service
services:
  server:
    container_name: web-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=$PORT
    command: npm run start:dev
    restart: on-failure
    volumes:
      - ./src:/usr/app/src
    environment:
      - DB_HOST=db
    ports:
      - $PORT:$PORT
    depends_on:
       db:
         condition: service_healthy
    networks:
      - home-lib-network
  db:
    container_name: db
    image: postgres:15.3-alpine
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/var/lib/postgresql/data/logs
    restart: always
    user: $POSTGRES_USER
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $DB_PORT:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - home-lib-network
volumes:
  db-data:
    driver: local
networks:
  home-lib-network:
    driver: bridge